import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.stream.Collectors;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        // Gets random internet quote
//        InternetQuoteGetter internetQuoteGetter = new InternetQuoteGetter();
//        Quote randomQuote = internetQuoteGetter.getInternetQuote();
//        System.out.println(randomQuote.toString());

        // Gets random quote from the list of saved quotes
        FileQuoteGetter fileQuoteGetter = new FileQuoteGetter();
        Path file = Paths.get("./resources/recentquotes.json");
        Quote[] quotes = fileQuoteGetter.getFileQuotes(file);
        int randomNumber = fileQuoteGetter.getRandomNumber(quotes.length);
        System.out.println(quotes[randomNumber].toString());



        // Search for
//        if (args.length > 0) {
//            if (args[0].equals("author")){
//                System.out.println(args[0]);
//                System.out.println(Quote.searchAuthor(quotes, args[1]));
//            }
//            else if (args[0].equals("contains")){
//                System.out.println(Quote.searchContains(quotes, args[1]));
//            }
//        } else {
//            System.out.println(quotes[rand].toString());
//        }
    }
}
